### ISSUE TITLE
Request: Configurable block limit

### ISSUE THREAD

**Issue by TheDeviantCrafter** [arlyon/veining#10]
I was able to break about five stacks of ore with a Veining 3 diamond pickaxe. Since my pack has giant ore veins and I want to encourage automatic mining, this causes some balance problems.

I'd like to be able to set a limit on how many blocks the Veining enchantment can break.  Specifically, 5/10/15 depending on the level of the enchantment.

**Comment by arlyon** [comment]
That should be a fairly easy to add. The feature is in felling and I thought I had added it here too but I guess not so it's on the way 👍
