### ISSUE TITLE
Veining on a pickaxe causes inability to properly mine modded tile entities.

### ISSUE THREAD

**Issue by border999** [arlyon/veining#11]
- Minecraft 1.12.2
- Forge: 14.23.3.2676
- Veining: 1.3.0

## Report Information

Veining put on a pickaxe causes it to be unable to properly mine modded tile entities.

## Steps to Reproduce

Put the Veining enchant on a pickaxe, have another mod installed to test on. (Thermal expansion or something.) Attempt to mine on of the machines, it will seem to disappear but the entity will not drop and you will be unable to stand on that block where the machine was.

## Forge Log

No reason in this case.

## Crash Log (if appropriate)
No.

**Comment by border999** [comment]
https://github.com/WayofTime/BloodMagic/issues/1300#issuecomment-386916153

**Comment by arlyon** [comment]
Thanks for the report. Null pointer came from passing a null into a function that shouldn't take null. Could have sworn the parameter was `@Nullable` though..

Fixed now.
