### ISSUE TITLE
Stops COFH:Core enchantment from working properly

### ISSUE THREAD

**Issue by sweetsosweet** [arlyon/veining#13]
## Version Information

- Minecraft 1.12.2
- Forge: 1.12.2-14.23.3.2698
- veining-1.3.1-1.12.x.jar
- CoFHCore-1.12.2-4.5.2.19-universal.jar
- RedstoneFlux-1.12-2.0.2.3-universal.jar
- VanillaTools-1.12.2-1.0.0.1-universal.jar

## Report Information

COFH:Core adds the enchantment smelting, that no longer works when veining is applied to the same tool. Tool works with only smelting (which smelts an ore, eg: iron ore into ingots), but once you add veining to the same tool, the ore block is dropped instead.

See issue [cross-posted here](https://github.com/CoFH/Feedback/issues/1131) for comments regarding this.

**Comment by arlyon** [comment]
Thanks for the heads up. Following up now.

edit: got a fairly good solution but still polishing things up
