### ISSUE TITLE
tinkers' modifier / trait support

### ISSUE THREAD

**Issue by arlyon** [arlyon/veining#7]
I'm going to explore support for tinkers' modifier and trait.

**Comment by vertex101** [comment]
any update on this ?

**Comment by arlyon** [comment]
I've got some free time this weekend so I'll see what I can do

**Comment by arlyon** [comment]
Going to leave this open for a while for any comments about balance. I've added the trait but I'm not sure what material it should apply to to be balanced so go ahead and leave suggestions below. I'm not super familiar with tinkers construct so let me know what your ideas are.

**Comment by vertex101** [comment]
well i think setting it to stone should be fine as with the new tinkers and the sharping kits you can make a quick high level mining tool if that is what your talking about

**Comment by Zodsmar** [comment]
I hope this is getting added to Felling mod too. Atm using Just enough resources Tinkers tools say that I can add the enchantment to them but I don't know how. For balance I think anything Iron+ related. Looking forward to seeing this on tinkers tools thanks! (Eta on how soon would be amazing building a modpack so sooner the better 👍 )

**Comment by TheDeviantCrafter** [comment]
I don't think it should require a specific Tinkers' material level. Reaching cobalt level isn't hard unless you're in an expert mode pack. Instead I'd make the modifier itself expensive.

**Comment by arlyon** [comment]
I've been experimenting and have added a modifier that takes only a single modifier slot but can be levelled up to level 10, each increasing the number of blocks mined out. This approach feels quite natural during my play but you guys know best so let me know what you think. Apply an explosive emerald to any tool in the Tool Forge.
