### ISSUE TITLE
Geolosys and Veining

### ISSUE THREAD

**Issue by ghost** [arlyon/veining#9]
## Version Information

- Minecraft 1.12.2
- Forge: 14.23.2.2611
- Veining: 1.2.2

## Report Information

The Veining enchantment does not work with Geolosys veins.

## Steps to Reproduce

Install both Veining and Geolosys.
Enchant a pickaxe with the Veining enchantment and attempt to break a Geolosys vein.

## Forge Log

https://paste.ee/p/0jOXD

**Comment by arlyon** [comment]
Thanks for the report I was planning on fixing another one tomorrow as well so I'll see if I can get this one too

**Comment by arlyon** [comment]
resolved for 1.2.3
